DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  open_id VARCHAR (32) PRIMARY KEY COMMENT '用户的主键信息'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';



DROP TABLE IF EXISTS AUTH_CLIENTS;
CREATE TABLE AUTH_CLIENTS(
UUID VARCHAR(48) PRIMARY KEY COMMENT '主键',
CLIENT_ID VARCHAR(32) UNIQUE NOT NULL COMMENT '客户端凭证',
CLIENT_SECRET VARCHAR (128) NOT NULL COMMENT '客户端验证信息',
GRANT_TYPE VARCHAR (32) NOT NULL COMMENT '授权类型',
REDIRECT_URL VARCHAR(2048) DEFAULT NULL COMMENT '回调地址,可以为空'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='授权客户端表';

